# Generated by Django 5.2.2 on 2025-09-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='otop_search_thailand.province')),
            ],
            options={
                'indexes': [models.Index(fields=['province', 'category'], name='otop_search_provinc_31acb1_idx')],
            },
        ),
    ]
