# Generated by Django 5.2.2 on 2025-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otop_search_thailand', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='otop_search_name_384b7c_idx'),
        ),
    ]
